[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
user-dev.daws88s.online

[cart]
cart-dev.daws88s.online

[mysql]
localhost

[shipping]
shipping-dev.daws88s.online

[rabbitmq]
localhost

[payment]
payment-dev.daws88s.online

[frontend]
frontend-dev.daws88s.online

